V1.0
remomax/Chess-ELO-Calcuator pull request #25
Opened 2024-03-29 10:19 UTC by remomax

2024-03-29 14:51 UTC, tpogadlc24 requested changes

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddGameController.php
> +            echo '0 results';
besser kein echo in logik

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddGameController.php
> +        $sql = "SELECT username FROM person WHERE id = '$id_black' LIMIT 1";
variablen in strings können zu unvorhersehbaren problemen führen. besser konkatenieren ( 'a' . $b . 'c' ).
insbesondere in sql queries sollten keine variablen stehen. vor allem dann nicht, wenn die eingabe vom benutzer kommt.

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddGameController.php
> +            while($row = $result->fetch_assoc()) {
statt while schleife (die nur ein mal läuft), kann man sich auch die result row direkt holen.

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddGameController.php
> +        $sql = "SELECT username FROM person WHERE id = '$id_black' LIMIT 1";
dies ist aufgabe von PersonRepository und sollte nicht manuell gemacht werden

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddGameController.php
> +        elseif ($username !== $username_black) {
kann alles in einer zeile gemacht werden
if ($username !== $username_white && $username !== $username_black) {

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddPersonController.php
> +    $mail->Body = 'Guten Tag ' . $fname . ", "  . $lname  . '<br>Gehen sie auf: <a href="verify.php">Hier</a> und verifiziren sie sich mit ihrem Verifikations Code: ' . $verify_id .
verify.php sollte eine route für einen controller sein

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddPersonController.php
> +    $mail->Body = 'Guten Tag ' . $fname . ", "  . $lname  . '<br>Gehen sie auf: <a href="verify.php">Hier</a> und verifiziren sie sich mit ihrem Verifikations Code: ' . $verify_id .
"verifizieren"

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddPersonController.php
> +    $mail->Body = 'Guten Tag ' . $fname . ", "  . $lname  . '<br>Gehen sie auf: <a href="verify.php">Hier</a> und verifiziren sie sich mit ihrem Verifikations Code: ' . $verify_id .
"Sie" als anrede groß

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/AddPersonController.php
> +        '<br>(Link: http://localhost:8000/verify.php) Dies Ist nur Eine Test Mail und das verify Funkzionirt noch nicht';
"funktioniert"

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/PasswordChangeController.php
> +        if ($password_new == $password_old) {
=== verwenden

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/PasswordChangeController.php
> +        $mail->Username = 'maximilian.schwarz@igs-edigheim.de'; // SMTP-Benutzername (deine Microsoft 365 E-Mail-Adresse)
das steht alles an andere stelle schonmal. sollte in eine mail klasse, damit der code nicht wiederholt wird und bugs/erweiterungen an verschiedenen stellen gemacht werden müssen

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/RealVerifyController.php
> +public function Index(): void
achte auf code style für bessere lesbarkeit. phpstorm kann das automatisch machen mit cmd+option+L

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/RealVerifyController.php
> +        echo "<br>";
redirect statt echo

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/Controller/RealVerifyController.php
> +            "true",
bool werte sollten nicht als string gespeichert werden. in der datenbank ist da einfachste, 1 oder 0 zu verwenden, was einfach als bool gelesen werden kann

2024-03-29 14:51 UTC, tpogadlc24 commented on web/app/routes.php
> +SimpleRouter::get('/RealVerifyController', [\Praktikant\Praktikum\Controller\RealVerifyController::class, 'index'], ['as' => 'RealVerifyController.get']);
controller nicht in die route schreiben. die routen sollten benutzerfreundlich sein

2024-03-29 14:51 UTC, tpogadlc24 commented on web/templates/html_main.php
>      if ($_SESSION == [])
verwende immer klammern { }

2024-03-29 14:51 UTC, tpogadlc24 commented on web/templates/html_main.php
>      if ($_SESSION == [])
ob die session komplett leer ist ist sehr unspezifisch. prüfe besser auf die werte, die du verwendest.
oder noch besser: erstelle eine klasse, welche sich um die session kümmert. dann kannst du dort alle funktionen aufnehmen, die du brauchst.

2024-03-30 10:36 UTC, remomax reviewed
teest

2024-03-30 10:36 UTC, merged